name: "Composite action attempt 1"
description: "Try to get this composite action to run in a private repo"

inputs:

runs:
  using: "composite"

  #env:
  #  BASE_URL: ${{ secrets.SERVER_URL }}
  #  PLAYGROUND_EMAIL: ${{ secrets.PLAYGROUND_EMAIL }}
  #  PLAYGROUND_PASSWORD: ${{ secrets.PLAYGROUND_PASSWORD }}
  #  PLAYGROUND_ID: ${{ secrets.PLAYGROUND_ID }}
  #  EXTRA_LANGUAGES: ${{ secrets.EXTRA_LANGUAGES }}

  steps:
    - name: Env vars
      env:
        BRANCH_PATH: ${{ github.ref }}
      run: echo "REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
        shell: bash
      run: echo "Repo address is $REPO_URL"
        shell: bash
      #run: echo "BRANCH_PATH=${{ github.ref }}" >> $GITHUB_ENV
      #  shell: bash
      run: echo "$BRANCH_PATH"
        shell: bash
