name: "Composite action attempt 1"
description: "Try to get this composite action to run in a private repo"

runs:
  using: "composite"

  #  BASE_URL: ${{ secrets.SERVER_URL }}
  #  PLAYGROUND_EMAIL: ${{ secrets.PLAYGROUND_EMAIL }}
  #  PLAYGROUND_PASSWORD: ${{ secrets.PLAYGROUND_PASSWORD }}
  #  PLAYGROUND_ID: ${{ secrets.PLAYGROUND_ID }}
  #  EXTRA_LANGUAGES: ${{ secrets.EXTRA_LANGUAGES }}

  steps:
    - name: env vars
      shell: bash
      run: echo "env var test"
      env:
        BRANCH_PATH: ${{ github.ref }}
    - run: echo "$BRANCH_PATH"
      shell: bash
