name: "Composite action attempt 1"
description: "Try to get this composite action to run in a private repo"

inputs:
  SERVER_URL:
    description: 'The url of your docassemble server. This should be in your github SECRETS or the SECRETS of your org.'
    required: true
  PLAYGROUND_EMAIL:
    description: 'The email of your docassemble testing account. This should be in your github SECRETS or the SECRETS of your org.'
    required: true
  PLAYGROUND_PASSWORD:
    description: 'The password of your docassemble testing account. This should be in your github SECRETS or the SECRETS of your org.'
    required: true
  PLAYGROUND_ID:
    description: 'The id of your docassemble testing account. This should be in your github SECRETS or the SECRETS of your org.'
    required: true
  EXTRA_LANGUAGES:
    description: 'Other languages you want to test. This should be in your github SECRETS or the SECRETS of your org.'
    required: true
    default: ''
    # TODO: Check if we really need the `if` for extra languages

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: "12"
    - name: Run ALKiln tests
      env:
        REPO_URL: "${{ github.server_url }}/${{ github.repository }}"
        BRANCH_PATH: ${{ github.ref }}
        BASE_URL: ${{ inputs.SERVER_URL }}
        PLAYGROUND_EMAIL: ${{ inputs.PLAYGROUND_EMAIL }}
        PLAYGROUND_PASSWORD: ${{ inputs.PLAYGROUND_PASSWORD }}
        PLAYGROUND_ID: ${{ inputs.PLAYGROUND_ID }}
        EXTRA_LANGUAGES: ${{ inputs.EXTRA_LANGUAGES }}

      run: |
        echo -e "Repo is $REPO_URL\nBranch is $BRANCH_PATH\nServer is $BASE_URL\nPassword is ${{ inputs.PLAYGROUND_PASSWORD}}"
        npm install
        npm run setup
        npm run takedown
      shell: bash

        # npm run test -- ${{ github.event.inputs.tags && format('"--tags" "{0}"', github.event.inputs.tags) }}
