name: "Composite action attempt 1"
description: "Try to get this composite action to run in a private repo"

inputs:
  SERVER_URL:
    description: 'The url of your docassemble server'
    required: true

runs:
  using: "composite"

  #  BASE_URL: ${{ secrets.SERVER_URL }}
  #  PLAYGROUND_EMAIL: ${{ secrets.PLAYGROUND_EMAIL }}
  #  PLAYGROUND_PASSWORD: ${{ secrets.PLAYGROUND_PASSWORD }}
  #  PLAYGROUND_ID: ${{ secrets.PLAYGROUND_ID }}
  #  EXTRA_LANGUAGES: ${{ secrets.EXTRA_LANGUAGES }}

  steps:
    - run: echo "BRANCH_PATH=${{ github.ref }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "$BRANCH_PATH"
      shell: bash
    - run: echo "REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
      shell: bash
    - run: echo "Repo address is $REPO_URL"
      shell: bash
    - run: echo "Server url is $INPUT_SERVER_URL"
      shell: bash
