name: "Composite action attempt 1"
description: "Try to get this composite action to run in a private repo"

inputs:
  SERVER_URL:
    description: 'The url of your docassemble server. This should be in your github SECRETS or the SECRETS of your org.'
    required: true
  PLAYGROUND_EMAIL:
    description: 'The email of your docassemble testing account. This should be in your github SECRETS or the SECRETS of your org.'
    required: true
  PLAYGROUND_PASSWORD:
    description: 'The password of your docassemble testing account. This should be in your github SECRETS or the SECRETS of your org.'
    required: true
  PLAYGROUND_ID:
    description: 'The id of your docassemble testing account. This should be in your github SECRETS or the SECRETS of your org.'
    required: true
  EXTRA_LANGUAGES:
    description: 'Other languages you want to test. This should be in your github SECRETS or the SECRETS of your org.'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
      shell: bash
    - run: echo "BRANCH_PATH=${{ github.ref }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "BASE_URL=${{ inputs.SERVER_URL }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "PLAYGROUND_EMAIL=${{ inputs.PLAYGROUND_EMAIL }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "PLAYGROUND_PASSWORD=${{ inputs.PLAYGROUND_PASSWORD }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "PLAYGROUND_ID=${{ inputs.PLAYGROUND_ID }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "EXTRA_LANGUAGES=${{ inputs.EXTRA_LANGUAGES }}" >> $GITHUB_ENV
      if: ${{ inputs.EXTRA_LANGUAGES != '' }}
      shell: bash
    - run: echo -e "Repo is $REPO_URL\nBranch is $BRANCH_PATH\nServer is $BASE_URL\nPassword is ${{ inputs.PLAYGROUND_PASSWORD}}"
      shell: bash
    - name: Check for file
      run: >-
        FILE=./package.json
        if test -f "$FILE"
        then
          echo "$FILE exists."
        else
          echo "File does not exist"
        fi
      shell: bash

